/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class Paleta */

#ifndef _Included_Paleta
#define _Included_Paleta
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     Paleta
 * Method:    printText
 * Signature: (LColor;)V
 */
JNIEXPORT void JNICALL Java_Paleta_printText
  (JNIEnv *, jobject, jobject);

#ifdef __cplusplus
}
#endif
#endif
